# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: data cron job

on:
  push:
  schedule:
    - cron: "0 9 * * *"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
    - run: npm install
    - run: npm start
    
    - name: Commit changes
      uses: EndBug/add-and-commit@v9
      with:
        author_name: undefined
        author_email: johann@objekt.stream
        message: 'update data'
        add: '*'
